services:
  app:
    build:
      context: https://github.com/Obion-County-Board-of-Education/FuelTime.git
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped
